# Generated by Django 5.2.3 on 2025-06-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilio_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelis', models.CharField(help_text='Iveskite masinos modeli ', max_length=200, verbose_name='Modelis')),
                ('marke', models.CharField(help_text='Iveskite automobilio marke', max_length=200, verbose_name='Automobilio Marke')),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(help_text='Iveskite valstybini numeri', max_length=7, verbose_name='Valstybinis Numeris')),
            ],
        ),
    ]
