# Generated by Django 5.2.3 on 2025-06-13 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(help_text='Iveskite valstybini numeri', max_length=7, verbose_name='Valstybinis Numeris')),
                ('auto_model', models.CharField(help_text='Iveskite masinos modeli ', max_length=200, verbose_name='Modelis')),
                ('vin_number', models.CharField(help_text='Iveskite VIN koda', max_length=20, verbose_name='VIN Kodas')),
                ('client_name', models.CharField(max_length=20, verbose_name='Klientas')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Iveskite masinos modeli ', max_length=200, verbose_name='Modelis')),
                ('make', models.CharField(help_text='Iveskite automobilio marke', max_length=200, verbose_name='Gamintojas')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Kiekis')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('price', models.IntegerField(verbose_name='Kaina')),
            ],
        ),
        migrations.DeleteModel(
            name='Automobilio_modelis',
        ),
        migrations.DeleteModel(
            name='Automobilis',
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.carmodel'),
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.car', verbose_name='Automobilis'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.order', verbose_name='Uzsakymas'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.service', verbose_name='Paslauga'),
        ),
    ]
